unique_ids:
  assets:
    dashboard.html: ZWKUZFZGYZSYV7X2F34CYFYZQXITCEUQ
    single-column.html: G2IMQSWTYUTFBL637KB6NKM2ETHOF5IV
    theme.css: RUQOTVV7XKMBPO4ERZAQ2X7NHTSOZ2RT
  forms:
    ChangePassword: WZQLL7CAJCUYKI5JICF6JBBLADSHPTKV
    Home: E543JOQDTFKLTQBYIEEJE6HCAU4SP3RI
    Login: 27AVBLNJ7Q5NPXYW4MD7MPSKULENSFGD
    Logout: 2E7Y5B2QE3FJLOHKS5F62NEZIEXFS7Y6
  modules:
    Module1: KQRK5R4GJ5LPVRSBYUPGOMMLZNFWXDEW
  scripts: {}
  server_modules: {}
